name: "Test Raku"
on:
  push:
    paths:
      - "**.rakumod"
      - "META6.json"
      - ".github/workflows/test.yaml"
  pull_request:
    paths:
      - "**.rakumod"
      - "META6.json"
      - ".github/workflows/test.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: jjmerelo/raku-test:latest
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name : Install cmark
        run: apk add libcmark && cp /usr/lib/libcmark.so.0.30.2 /usr/lib/libcmark.so
      - name: Test
        run: zef --debug test .


